spring.application.name=demo


# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tradingexchange
spring.datasource.username=postgres
spring.datasource.password=Yashdoinpostgres@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080